Youtube transcripts
learlab/itell-api pull request #28
Opened 2023-11-04 20:16 UTC by wesleygmorris

Added transcript generation to the api. If a chunk includes a youtube link, it will generate a transcript for that link in a TranscriptResults object. If the chunk does not include a youtube link, or if the youtube link does not include a transcript, it returns None in the TranscriptResults object.

2023-11-05 03:55 UTC, jchoi92k commented on models/transcript.py
> +    url: Optional[str] = None
Are `url`s supposed to be optional? Maybe
```python
url: str
```

2023-11-05 04:04 UTC, jchoi92k commented on pipelines/transcript.py
> +        video_code = url.split('/')[-1][-11:]
I think this is fine, but we could also use urllib which is included in Python 3 standard library
```python
from urllib import parse
url_parsed = parse.urlparse(url)
qsl = parse.parse_qs(url_parsed.query)
video_code = qsl['v'][0]
```

2023-11-05 04:16 UTC, jchoi92k commented on pipelines/transcript.py
> +            self.timestamps=True
`start_time` and `end_time` are optional but have no default values here so they need to be added in.
Also should account for cases where only end_time is provided.

```python
def __call__(self, url: str, start_time: int = None, end_time: int = None):
     self.timestamps = start_time or end_time
```

2023-11-05 16:39 UTC, jchoi92k commented on src/get_transcript.py
> +        )[0]
If the plan is to make this part of the Strapi pipeline, I think the approach from the previous commit (where the url is provided instead of being grabbed from the Supabase db) is the one we want.

2023-11-05 18:36 UTC, langdonholmes requested changes
Left some comments about validating assumptions using Pydantic and suggestions to simplify the start/end time logic.

As Joon pointed out, the API request will contain the URL and start/stop times. We will not use SupaBase for this.

Please also return specific HTTPExceptions for possible problems:
- 500 Internal Server Error (ErrorType, could be an IndexError for unknown reasons)
- 400 Bad Request (start time after end of video)
- 404 Not Found (no transcript available)
- 406 Not Acceptable (not an appropriate YouTube link). Pydantic will handle this for you if you use a validator.

2023-11-05 18:36 UTC, langdonholmes commented on src/get_transcript.py
> +        )[0]
Joon is correct. URL should be in the API call. Supabase should not be involved at all here.

2023-11-05 18:36 UTC, langdonholmes commented on src/get_transcript.py
> +        video_code = url.split('/')[-1][-12:-1]
Please specify this video code logic using Pydantic (inside `models/transcript.py`) with comments as necessary. The RegEx here is unreadable and potentially error prone.

No need for the `timestamps` logic. Just set `start_time` and `end_time` to `None` if they are not specified.

2023-11-05 18:36 UTC, langdonholmes commented on src/get_transcript.py
> +
```python
       try:
           start_time = start_time or 0
           end_time = end_time or srt[-1]['start']
           transcript = ' '.join([x['text'] for x in srt if end_time >= x['start'] >= start_time])
           return transcript
        except IndexError? as e:
            # handle the error. return an informative error message.
```

1. What is `x`? Is this a word, an utterance, a microsecond of speech?
2. Not sure what type of errors you are intending to catch here, but let's return an appropriate HTTPException if errors are possible. e.g., if the specified start_time is longer than the video, there should be a separate error message for that. If the transcript we get from YouTube is empty or otherwise not the structure we expect, there should be a specific error for that.

2023-11-06 14:53 UTC, wesleygmorris commented on pipelines/transcript.py
> +        video_code = url.split('/')[-1][-11:]
Nice! Thanks!

2023-11-06 14:54 UTC, wesleygmorris commented on pipelines/transcript.py
> +            self.timestamps=True
This is fixed in src.get_transcript.py

2023-11-06 14:59 UTC, wesleygmorris commented on src/get_transcript.py
> +
1. changed the notation
2. I'm not familiar with HTTPException and I couldn't find it being used elsewhere in the codebase, aside from in main.py. I added informative error messages for anticipated problems in `src.get_transcript.py`, though

2023-11-06 15:23 UTC, jchoi92k commented on models/transcript.py
> +    end_time: int = None
Probably a design choice but it seems having a separate input base model for inputs with urls in `base.py` and inheriting from that class fits better with the current setup.

2023-11-06 15:41 UTC, jchoi92k commented on src/get_transcript.py
> +        return transcript
Indentation looks weird.
400 bad request might fit our purpose here, so:
```python
raise HTTPException(status_code=400, detail="Start time is beyond the range of the video")
```

2023-11-06 16:22 UTC, jchoi92k commented on models/transcript.py
>      transcript: Optional[str] = None
Probably don't want this to be optional.

2023-11-06 17:05 UTC, wesleygmorris commented on src/get_transcript.py
> +        return transcript
Done.

2023-11-06 17:06 UTC, wesleygmorris commented on models/transcript.py
> +    end_time: int = None
I think the only use we have for urls is transcript generation... Unless there's something else I don't know about.

2023-11-06 17:07 UTC, wesleygmorris commented on models/transcript.py
>      transcript: Optional[str] = None
I made it optional so that the function would return `None` if the function failed for some reason. But since we are returning errors I think you are right. It's updated now.

2023-11-08 15:47 UTC, langdonholmes commented on models/transcript.py
> +    end_time: int = None
Agree with Wes, this seems pretty specific to youtube links.

2023-11-08 15:48 UTC, langdonholmes commented on src/get_transcript.py
> +
Looks good. I'll run some tests to confirm.

2023-11-08 18:33 UTC, langdonholmes approved these changes
This is nearly ready to merge in. I will push some of my own commits and then ask Joon to deploy.

The code was broken in several places, but that's not your fault since the vLLM integration has made it hard to test with a GPU.

- Added `HTTPException` import
- Fixed Pydantic model specification (must use Optional[] to make the `int` nullable)
- pip-compile the requirements
- removed assert statement from `get_transcript.py`. This caused an internal server error with `www.youtube.com` and `youtube.com` type URLs (no `https://`), which is both an uninformative error and also not needed because these URLs are totally valid and work just fine otherwise.
- made `generate_transcript()` a simple function. There is no need to structure this as a class because it has no state.

2023-11-08 18:35 UTC, merged