Adds the delete/unused route
learlab/itell-api pull request #46
Opened 2024-04-24 19:43 UTC by kyleburgess2025

Added route that deletes all unused chunks in the vector store, given a list of chunks in STRAPI

2024-04-25 15:46 UTC, langdonholmes commented on src/embedding.py
> +            db.table("embeddings").delete().eq("chunk", chunk['chunk']).execute()
Super minor, but I'd suggest using the Black Formatter. I think it is already included in the dev container. Should help with consistency regarding double/single quotes.

2024-04-25 15:48 UTC, langdonholmes commented on src/main.py
> +logging.basicConfig(level=logging.WARNING)
I think I was using this for more detailed logging in production, which might be an abuse of the log level system. We should continue work on improving logging either way (possibly setting more appropriate log levels so that we are not setting DEBUG in production).

2024-04-25 16:12 UTC, langdonholmes requested changes
Kyle, this looks great. I am requesting some super minor changes.

1. delete/unused --> delete/embedding (the reason for deleting isn't relevant, as we might use this endpoint for other deletion reasons)
2. Use single API call to supabase to delete chunks rather than multiple API calls in a loop (if possible, I haven't tested the supabase API).

Will this also work for deleting entire pages? e.g., Can Strapi issue an API call to /delete/embedding as an onDelete event? It looks like Strapi could just send a POST request with an empty chunk list to delete the entire page. Unused pages shouldn't cause any problems in the short term, but they could clutter up the vector-store over time.

Lastly, I'm using the Black formatter for this repository. I'm not picky about formatting, but I find it helpful to let Black handle it automatically.

2024-04-26 18:38 UTC, kyleburgess2025 commented on src/embedding.py
> +    for chunk in current_slugs:
Changed in most recent commit!

2024-04-26 18:39 UTC, kyleburgess2025 commented
> Kyle, this looks great. I am requesting some super minor changes.
> 
> 1. delete/unused --> delete/embedding (the reason for deleting isn't relevant, as we might use this endpoint for other deletion reasons)
> 2. Use single API call to supabase to delete chunks rather than multiple API calls in a loop (if possible, I haven't tested the supabase API).
> 
> Will this also work for deleting entire pages? e.g., Can Strapi issue an API call to /delete/embedding as an onDelete event? It looks like Strapi could just send a POST request with an empty chunk list to delete the entire page. Unused pages shouldn't cause any problems in the short term, but they could clutter up the vector-store over time.
> 
> Lastly, I'm using the Black formatter for this repository. I'm not picky about formatting, but I find it helpful to let Black handle it automatically.

Yes, I am currently adding the delete page functionality to Strapi. Once this PR is merged, I will make a PR that uses this route on both save and delete page

2024-04-27 01:15 UTC, langdonholmes commented on src/main.py
> +logging.basicConfig(level=logging.WARNING)
Should be fine! I will work on this at some point...

2024-04-27 01:15 UTC, langdonholmes approved these changes

2024-04-27 01:15 UTC, merged