Added API key requirement for using the API.
learlab/itell-api pull request #52
Opened 2024-05-29 18:52 UTC by kyleburgess2025

This PR requires all requests to have an API key. It checks the vector store to see if the owner of the key has the required permissions to use a route.

2024-05-30 20:35 UTC, langdonholmes requested changes
Kyle, this looks great.

I did some quick research on caching API keys, and a reasonable solution seems to be a "time-to-live" cache. Unfortunately, this will likely require another dependency.

The following looks good to me: [cache tools](https://cachetools.readthedocs.io/en/latest/?ref=vidavolta.io#cachetools.TTLCache)

2024-05-30 20:35 UTC, langdonholmes commented on src/main.py
> +@router.get("/", dependencies=[Depends(get_role)])
Can we leave this route open?

2024-05-30 20:35 UTC, langdonholmes commented on src/auth.py
> +def get_role(api_key_header: str = Security(api_key_header)):
I wonder if there is some method to keep the key cached? This will introduce a lot of database calls.

2024-05-31 17:21 UTC, kyleburgess2025 commented
@langdonholmes I've made the changes you requested, but I want to make 100000% sure it's working - could you try testing on your end?

2024-05-31 19:04 UTC, langdonholmes approved these changes
Looks great. Let me know if I should deploy this.

2024-05-31 20:05 UTC, merged