Add routes for creating/deleting API keys
learlab/itell-api pull request #53
Opened 2024-05-30 03:12 UTC by kyleburgess2025

2024-05-30 20:47 UTC, langdonholmes requested changes
This looks great. I made some comments on the parent PR that also apply here, otherwise this is ready to go from my POV -- just suggesting that insufficient privileges should get a 403 Forbidden status code.

2024-05-30 20:47 UTC, langdonholmes commented on src/api_keys.py
> +        raise HTTPException(status_code=400, detail="Role must be 'developer' or 'deployment'")
Pretty sure this should be 403 forbidden.

Just a wording thing, but I'd prefer `detail=f"The {api_key.role} role is not authorized to create new API keys."`

2024-05-30 20:47 UTC, langdonholmes commented on src/auth.py
> +
Can we return early if no API key is provided?

2024-05-31 17:22 UTC, kyleburgess2025 commented on src/api_keys.py
> +        raise HTTPException(status_code=400, detail="Role must be 'developer' or 'deployment'")
This check ensures that the new API key has a valid role, it doesn't check if the user has the required permissions to create the key - that is done elsewhere. Should I still make the change?

2024-05-31 18:05 UTC, langdonholmes commented on src/api_keys.py
> +        raise HTTPException(status_code=400, detail="Role must be 'developer' or 'deployment'")
Gotcha, my bad. I think HTTP 400 is correct in this case.

That said, I'll probably add an enum to src/models to handle this validation. I think it will be a bit more clear in terms of how to update the allowed roles.

2024-06-05 04:57 UTC, langdonholmes approved these changes

2024-06-05 05:04 UTC, merged