Using local FAISS for page similarity and chunk retrieval
learlab/itell-api pull request #73
Opened 2024-08-29 19:21 UTC by kyleburgess2025

I used Conda to install FAISS... see https://github.com/facebookresearch/faiss/blob/main/INSTALL.md

2024-08-31 15:56 UTC, langdonholmes requested changes
Looks very close. Most of comments pertain to simple housekeeping stuff, but I am wondering if there's a better way to handle:

1. Subsetting the vector store to get matches for a specific page or volume. We are wasting a fair bit of compute by filtering after the similarity queries. I'm assuming you found it difficult/impossible to do this with FAISS?
2. Getting top X least similar responses. Again, this may be due to a limitation with FAISS -- I'm not sure. Could you explain what you have tried and/or provide some reference stating that this is not possible with FAISS?

2024-08-31 15:56 UTC, langdonholmes commented on src/dependencies/faiss.py
> +    return EmbeddingPipeline()(text).tolist()[0]
I think this will construct a new pipeline every function call, which loads a transformer model onto the GPU which then needs to be garbage collected. We should avoid doing this, I think.

2024-08-31 15:56 UTC, langdonholmes commented on src/dependencies/faiss.py
> +                print(f"Skipping {data['chunk']} due to incorrect embedding length")
This should be a log rather than a `print`. I'm surprised that the return value for ["embedding"] appears to be a string rather than a JSON array... 

Can we use `json` or `ast.literal_eval` instead of manually parsing the string?

2024-08-31 15:56 UTC, langdonholmes commented on src/dependencies/faiss.py
> +            arr = np.array([float(i) for i in embedding])
`np.asarray(embedding, dtype=np.float32)` should do the trick.

2024-08-31 15:56 UTC, langdonholmes commented on src/dependencies/faiss.py
> +        print(f"Indexing complete. {index.ntotal} embeddings indexed.")
We should clean up print statements before merging. These would make fine INFO logs.

2024-08-31 15:56 UTC, langdonholmes commented on src/dependencies/faiss.py
> +        for doc in search_docs:
IMO, a list comprehension would be cleaner here.

2024-08-31 16:12 UTC, langdonholmes commented
Some additional thoughts:

1. The Supabase dependency currently [includes its own copy of the embedding pipeline](https://github.com/learlab/itell-api/blob/abdda39e7a3a69046ce3cc131a0507294cbbede1/src/dependencies/supabase.py#L19). This is not ideal, but is still better than creating and destroying an embedding pipeline every time an embedding is needed. The best solution would be to make the embedding pipeline a sub-dependency of the FAISS index. I think FastAPI will support this. Could you look into it?
2. Unfortunately, it looks like the proper solution to our indexing issues it to [build a separate index for each page](https://github.com/facebookresearch/faiss/wiki/FAQ#is-it-possible-to-dynamically-exclude-vectors-based-on-some-criterion). This makes sense to me, but will require significant changes to the PR. I think it's worth the trouble. We only ever run queries against pages (never against entire volumes). This does mean, however, that we would need to run mutltiple queries when performing RAG, because we also want to include the iTELL help documentation. In this case, we would query the user's current page + the iTELL help documentation (which is a single page volume).
3. Since we are using the L2-norm + Euclidean distance as a proxy for cosine similarity, all our embeddings are unit vectors. I think this means that we can simply [multiply the query vector by [-1] to get the least similar embeddings](https://github.com/facebookresearch/faiss/issues/1063#issuecomment-567218844). I don't know linear algebra, though, so if you are able to correct me or confirm me on this, I'd appreciate it!

2024-08-31 20:49 UTC, kyleburgess2025 commented on src/dependencies/faiss.py
> +    return EmbeddingPipeline()(text).tolist()[0]
I've added the pipeline to a private variable... would this help?

2024-08-31 20:52 UTC, kyleburgess2025 commented
@langdonholmes I've switched to using the GPU for the FAISS operations and the chunk retrieval has sped up severely - to 0.0509798526763916 seconds for finding the most similar module and to 0.020622730255126953 for finding the least similar module. I'm wondering if any further optimizations would be necessary, given how miniscule the difference would be.

2024-08-31 20:54 UTC, kyleburgess2025 commented on src/dependencies/faiss.py
> +        print(f"Indexing complete. {index.ntotal} embeddings indexed.")
done

2024-08-31 20:57 UTC, kyleburgess2025 commented on src/dependencies/faiss.py
> +        for doc in search_docs:
done

2024-08-31 21:00 UTC, kyleburgess2025 commented on src/dependencies/faiss.py
> +            arr = np.array([float(i) for i in embedding])
Did this, but removing `astype(np.float32)` from the `normalize_L2` threw type errors. Keeping it as is for now

2024-08-31 21:03 UTC, kyleburgess2025 commented
Other notes - 

- I'm going to try multiplying the query by -1 later on today... I'll let you know how that goes.
- The ID selector thing is possible, but the ID must be an integer, which somewhat confuses things. I could have the ID be an 8-digit integer hash of the page title with another 8-digit integer hash of the chunk? There's definitely a way to make it work for our case, but as mentioned before, the performance gains might not be that noticeable. Thoughts?

2024-08-31 22:33 UTC, langdonholmes commented
I'm surprised to see that much improvement just by switching to the GPU. Makes me think we are doing more compute than should be necessary, but whatever... You are right that .05 seconds is plenty fast for our purposes ;-). Let's not worry about the IDSelector stuff right now.

I do want to see some method for preserving the EmbeddingPipeline, so we aren't initializing a new one with every function call. It would also be great if multiplying by -1 works for retrieving the least similar chunk. I think we have a few hundred chunks in the vector store already, so finding the least similar of the top 1,000 most similar doesn't seem like a good long-term solution.

This is very close!

2024-09-01 19:53 UTC, kyleburgess2025 commented
@langdonholmes What do you have in mind for preserving the EmbeddingPipeline? I'm not 100% sure how to do it.

2024-09-01 19:55 UTC, kyleburgess2025 commented
Also, for the least similar chunk, I think multiplying by -1 would work but we would still have to get the top 500 or so chunks, since we are not filtering by ID and the least similar chunks are likely from other textbooks

2024-09-01 23:55 UTC, langdonholmes commented
Well, I am pretty sure loading the model would take more than 0.05 seconds, so I'm not totally sure what's going on. I'll try to do some of my own testing tomorrow.

Anyway, It would be fine to just assign a copy of the Embedding model to an attribute of the FAISSWrapper class instance. I can figure out sub-dependencies later.

Good point about the least similar chunks. I still think multiplying by -1 will simplify the code a fair bit, so I'd say it's worth doing.

2024-09-03 16:43 UTC, kyleburgess2025 commented
@langdonholmes Added the negative query for least similar chunks!

2024-09-06 15:29 UTC, kyleburgess2025 commented
@langdonholmes could you take a look at the PR?

2024-09-08 19:43 UTC, langdonholmes approved these changes

2024-09-08 19:43 UTC, merged